### ISSUE TITLE
Interpreting Output of main.py

### ISSUE THREAD

**Issue by apclypsr** [RobRomijnders/AE_ts#4]
Hi Rob,

Very interesting work. Just wondering, once I run main.py successfully and it outputs a bunch of files, how do I process these files to actually get to identifying the clusters of variables?

Thanks,
Lou

**Comment by tharunShiv** [comment]
Hi apclypsr, May I know how you obtained it?

**Comment by apclypsr** [comment]
I'm not sure I ever figured this out..

**Comment by usarawgi911** [comment]
Hi tharunShiv and apclypsr, could you figure it out yet?

**Comment by RobRomijnders** [comment]
Hi @tharunShiv @apclypsr @usarawgi911 ! 

You can use the latent space of the auto-encoder for your favourite clustering algorithm

**Comment by RobRomijnders** [comment]
To be more precise, you can fetch the `Model.z_mu` [tensor](https://github.com/RobRomijnders/AE_ts/blob/master/AE_ts_model.py#L107).

That should give you a tensor of size `[num_samples, num_latent_dimensions]`, which feeds into any clustering algorithm, like K-means or Gaussian Mixtures
